### ISSUE TITLE
i download this game but open to get some errors please solve problem 

### ISSUE THREAD

**Issue by yashparmar71** [tameemsafi/shapematch-ios-swift#1]
i download this game but open to get some errors please solve problem 
i have convert in swift3 but get 19 errors 
please solve this tis immediately i have an emergency

**Comment by tameemsafi** [comment]
Thank you for your feedback. However, I am not maintaining this project. It was built for educational purposes.

**Comment by yashparmar71** [comment]
ok sir but i have use to develop this project please help me

**Comment by tameemsafi** [comment]
I don't provide support for this repository, please look online for some tutorials.
